Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2025
Var

acertos: inteiro

resposta: caractere

Inicio

acertos <- 0

escreval("Pergunta 1: Qual a capital do Brasil?")

escreval("a) Brasília")

escreval("b) Rio de Janeiro")

escreval("c) São Paulo")

escreval("d) Salvador")

leia(resposta)

se resposta = "a" entao

acertos <- acertos + 1

fimse

escreval("Pergunta 2: Qual é o maior planeta do Sistema Solar?")

escreval("a) Terra")

escreval("b) Júpiter")

escreval("c) Saturno")

escreval("d) Vênus")

leia(resposta)

se resposta = "b" entao

acertos <- acertos + 1

fimse

escreval("Pergunta 3: Quem escreveu 'Dom Casmurro'?")

escreval("a) Machado de Assis")

escreval("b) Clarice Lispector")

escreval("c) Monteiro Lobato")

escreval("d) José Saramago")

leia (resposta)

se resposta = "a" entao

acertos <- acertos + 1

fimse

escreval("Pergunta 4: Qual é o elemento quimico com o simbolo '0'?")

escreval("a) ouro")

escreval("b) Oxigênio")

escreval("c) Ósmio")

escreval("d) Óxido")

leia(resposta)

se resposta = "b" entao

acertos <- acertos + 1
fimse

escreval("Pergunta 5: Qual é o continente onde fica o Egito?")

escreval("a) Ásia")

escreval("b) Oceania")

escreval("c) Europa")

escreval("d) África")

leia (resposta)

se resposta = "d" entao

acertos <- acertos + 1
fimse

escreval("Pergunta 6: De quem é a famosa frase penso logo existo? ")

escreval("a) Platão")

escreval("b) Galileu Galilei")

escreval("c) Descartes")

escreval("d) Fransis Bacon")

leia(resposta)

se resposta = "c" entao

acertos <- acertos + 1
 fimse

escreval("Pergunta 7: Quantas casas decimais tem o número pi? ")

escreval("a) Dezenas")

escreval("b) Centenas")

escreval("c) Infinitas")

se resposta = "c" entao

acertos <- acertos + 1
fimse

escreval("Pergunta 7: Quantas casas decimais tem o número pi? ")

escreval("a) Dezenas")

escreval("b) Infinitas")

escreval("c) Centenas")

escreval("d) Milhares")

leia(resposta)

se resposta = "b" entao

acertos <- acertos + 1
fimse

escreval("Pergunta 8: Quantos elementos existem na tabela periódica?")

escreval("a) 113")

escreval("b) 109")

escreval("c) 108")

escreval("d) 118")

leia(resposta)

se resposta = "d" entao

acertos <- acertos + 1
fimse

escreval("Pergunta 9: Qual foi o pior ser humano da história? ")

escreval("a) Kain")

escreval("b) Luis Inácio Lula da Silva")

escreval("c) Napoleon Bonaparte")

escreval("d) Adolf Hitler")

leia(resposta)

se resposta = "d" entao

acertos <- acertos + 1
 fimse
 
 escreval("Pergunta 10: Em que ano nasceu Jair Messias Bolsonaro")
 
escreval("a) 1967")

escreval("b) 1942")

escreval("c) 1977")

escreval("d) 1955")

leia(resposta)

se resposta = "d" entao

acertos <- acertos + 1
 fimse
escreva ("Você acertou um total de", acertos," perguntas!")

Fimalgoritmo